In [1]:
import numpy as np

In [2]:
list_c = [1, 2, 3, 4]

In [3]:
type(list_c)

list

In [6]:
array_c = np.array(list_c)

In [7]:
type(array_c)

numpy.ndarray

In [8]:
array_c

array([1, 2, 3, 4])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr = np.random.randint(0, 100, 10)

In [17]:
arr

array([35, 99, 32, 79, 13, 32, 74, 48, 78, 56])

In [19]:
arr.max()

99

In [22]:
arr.argmin()

4

In [23]:
arr.mean()

54.6

In [25]:
arr.shape

(10,)

In [27]:
arr.reshape(5,2)

array([[35, 99],
       [32, 79],
       [13, 32],
       [74, 48],
       [78, 56]])

In [28]:
matrix = np.arange(0,100).reshape(10,10)

In [29]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
matrix[5,3]

53

In [32]:
matrix[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [33]:
matrix[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [34]:
matrix[:,3].reshape(10,1)

array([[ 3],
       [13],
       [23],
       [33],
       [43],
       [53],
       [63],
       [73],
       [83],
       [93]])

In [37]:
matrix[4:7,3:8]

array([[43, 44, 45, 46, 47],
       [53, 54, 55, 56, 57],
       [63, 64, 65, 66, 67]])

In [38]:
matrix[4:7,3:8] = 0

In [39]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42,  0,  0,  0,  0,  0, 48, 49],
       [50, 51, 52,  0,  0,  0,  0,  0, 58, 59],
       [60, 61, 62,  0,  0,  0,  0,  0, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])